server:
  port: 9000
  servlet:
    context-path: /seckill


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    mode: HTML5
    cache: false

  #连接池
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.46.250:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    druid:
      filters: stat,wall,slf4j,config
      max-active: 1000
      initial-size: 100
      max-wait: 500
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  #配置缓存
  #redis:
  #  port: 6379
  #  host: 106.13.46.250
  #  timeout: 3000
  #  jedis:
  #    pool:
  #      max-active: 8
  #      max-idle: 10
  #      max-wait: 3000
  #  database: 0
  #  password:


redis:
  host: 106.13.46.250
  port: 6379
  timeout: 10
  maxActive: 1000
  maxIdle: 500
  maxWait: 3

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.ct.seckill.domain,org.ct.seckill.dto
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    org.ct.seckill.* : debug